### ISSUE TITLE
If not logged into rdio, player will stop playing 30s and will not go to next song

### ISSUE THREAD

**Issue by malucky** [ammoio/ammo#130]

**Comment by ZicklePop** [comment]
@malucky Hey, I love this project so much. This appears to still be a bug? I am logged in to Rdio on the computer serving the playlist, do I need a paid account?

Thanks!

**Comment by deini** [comment]
Hey @JakeBilbrey I'm glad you like it! Unfortunately because of Rdio API limitations you can only stream 30 seconds without a paid account.

**Comment by ZicklePop** [comment]
Cool, no problem, thanks for the clarification.
